# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  mysql-service:
    image: mysql:5.7
    ports:
    - "3307:3306"
    volumes:
    - /home/namnd/Downloads/data/compose-store-data:/var/lib/mysql
    networks:
      - my-net
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=testapp
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-net
    depends_on:
      - mysql-service
  angular:
    image: angular-test
    ports:
    - "4200:80"
    expose:
      - "80"
    networks:
      - my-net
networks:
  my-net:
    driver: bridge
